version: '3.5'

networks:
  warper-network:
    name: warper-network
    driver: bridge

# volumes:
  
#   nestjs:
#     driver: local
#     name: nestjs
#     driver_opts:
#       type: none
#       device: /Users/majjig/Desktop/vl
#       o: bind
  
  # # front:
  # #   driver: local
  # #   name: front
  # #   driver_opts:
  # #     type: none
  # #     device: /Users/majjig/goinfre/ft_transcendence/src/front
  # #     o: bind

  # postgres:
  #   driver: local
  #   name: postgres
  #   driver_opts:
  #     type: none
  #     device:  /Users/majjig/goinfre/ft_transcendence/src/postgres
  #     o: bind

services:

  nestjs:
    container_name: nestjs
    build: ./src/backend
    env_file:
      - .env
    networks:
      - warper-network
    # volumes:
    #   - nestjs:/workspace
    ports:
      - "3000:3000"
      - "5555:5555"
    restart: unless-stopped
    depends_on:
      - postgres  
  postgres:
    container_name: postgres
    build: ./src/database
    env_file:
      - .env
    networks:
      - warper-network
    ports:
      - "5432:5432"
    # volumes:
    #   - postgres:/docker-entrypoint-initdb.d
    environment:
      - PGDATA=/var/lib/postgresql/custom-data
    restart: unless-stopped